# See LICENSE file for full copyright and licensing details.

from odoo import api, fields, models, _
from odoo.addons.account.models.partner import ResPartner

class ConvenioCliente(models.Model):
    _name = 'convenio.cliente'
    _description = 'Convenio de Clientes'

    name = fields.Char('Descripcion', size=128, required=True)
    code = fields.Char('Codigo de Convenio', size=128, required=True)

class HistorialClinico(models.Model):
    _name = 'historial.clinico'
    _description = 'Historial Clinico'

    _rec_name = 'nombre'

    @api.model
    def default_get(self, fields):
        # res = super(sale_order_invoice_wizard, self).default_get(fields)

        # res.update(ticket_ids=tickets)
        # contextual_self = self.with_context(default_load_default=True)
        res = super(HistorialClinico, self).default_get(fields)
        # res.update({'ticket_ids': tickets})
        res.update({'load_default': True})
        return res

    state = fields.Selection([('cancelada', 'Cancelada'), ('cita', 'Cita Agendada'), ('proceso', 'En Proceso'),
                              ('cerrada', 'Consulta Terminada')], 'Estado', default="cita")
    history_type = fields.Selection([
        ('Primaria', 'Patologia Primaria'),
        ('Historia', 'Historia'),
        ('Secundaria', 'Patologia Secundaria'),
                              ], 'Estado', default="Historia", compute='_get_default_hs')

    partner_id = fields.Many2one('res.partner', 'Paciente', domain=[('customer', '=', True)], required=True)
    convenio_id = fields.Many2one('convenio.cliente', 'Convenio')
    finalidad = fields.Selection([('8', ' 8 - Deteccion de Alteraciones de agudeza visual'), ('9', 'Otro') ], default='8')
    tipo_servicio = fields.Selection([('1', 'Primera Vez'), ('2', 'Control')], default='1', readonly=True)
    fecha = fields.Datetime('Fecha y Hora', default=fields.datetime.now())

    nombre = fields.Char('Nombre', related='partner_id.name')
    documento = fields.Char('Documento')

    motivo = fields.Text('Motivo de Consulta')

    ## antecedentes_familiares = fields.Text('Antecedentes Generales Familiares y Personales') ##
    is_licor = fields.Boolean('¿Consume licor constantemente?')
    is_fumador = fields.Boolean('¿Fuma cigarrillo?')
    is_lentes = fields.Boolean('¿Usa Lentes?')
    lentes_desc = fields.Text('¡Que tipo de lentes?')
    is_enfermedad_here = fields.Boolean('Enfermedad hereditaria')
    enfermedad_here_desc = fields.Text('Describe qué enfermedades')
    is_operaciones = fields.Boolean('Cirugias')
    operaciones_desc = fields.Text('Descrpcion Cirugias')
    is_alergias = fields.Boolean('Alergias')
    alergias_desc = fields.Text('Descripcion alergias')
    is_medicacion = fields.Boolean('Medicamentos')
    medicacion_desc = fields.Text('Descripcion que medicamentos')

    antecedentes_oculares = fields.Text('Antecedentes Oculares Familiares y Personales')

    ## Agudeza ##
    load_default = fields.Boolean('Cargar Valores', default=True)

    ## LENSOMETRIA
    lensometria_od = fields.Char('OD', size=128)
    lensometria_id = fields.Char('OI', size=128)

    ### Datos Historicos
    examen_anterior = fields.Char('Examen Segmento Anterior', size=128)
    examen_motor = fields.Char('Examen Motor', size=128)
    ishihara = fields.Char('Ishihara', size=128)
    estereopsis = fields.Char('Estereopsis', size=128)

    ## Refraccion y Queratometria

    queratometria_od = fields.Char('OD', size=128)
    refraccion_od = fields.Char('OD', size=128)
    refraccion_bajo_od = fields.Char('OD', size=128)

    queratometria_oi = fields.Char('OI', size=128)
    refraccion_oi = fields.Char('OI', size=128)
    refraccion_bajo_oi = fields.Char('OI', size=128)

    notas_queratometria_refraccion = fields.Text('Notas')
    ### RX USO ###
    rx_uso_od_esf = fields.Char('Rx uso OD ESF')
    rx_uso_od_cil = fields.Char('Rx uso OD CIL')
    rx_uso_od_eje = fields.Char('Rx uso OD EJE')
    rx_uso_od_add = fields.Char('Rx uso OD ADD')
    rx_uso_oi_esf = fields.Char('Rx uso OI ESF')
    rx_uso_oi_cil = fields.Char('Rx uso OI CIL')
    rx_uso_oi_eje = fields.Char('Rx uso OI EJE')
    rx_uso_oi_add = fields.Char('Rx uso OI ADD')
    ### AGUDEZA VISUAL ###
    av_sc_od_vp = fields.Char()
    av_sc_od_vl = fields.Char()
    av_sc_oi_vp = fields.Char()
    av_sc_oi_vl = fields.Char()
    av_cc_od_vp = fields.Char()
    av_cc_od_vl = fields.Char()
    av_cc_oi_vp = fields.Char()
    av_cc_oi_vl = fields.Char()

    ### RX FINAL ###
    rx_final_od_esf = fields.Char('Rx uso OD ESF')
    rx_final_od_cil = fields.Char('Rx uso OD CIL')
    rx_final_od_eje = fields.Char('Rx uso OD EJE')
    rx_final_od_add = fields.Char('Rx uso OD ADD')
    rx_final_oi_esf = fields.Char('Rx uso OI ESF')
    rx_final_oi_cil = fields.Char('Rx uso OI CIL')
    rx_final_oi_eje = fields.Char('Rx uso OI EJE')
    rx_final_oi_add = fields.Char('Rx uso OI ADD')
    rx_final_od_dp = fields.Char('Rx uso OD DP')
    rx_final_od_dnp = fields.Char('Rx uso OD DNP')
    rx_final_oi_dp = fields.Char('Rx uso OI DP')
    rx_final_oi_dnp = fields.Char('Rx uso OI DNP')
    rx_final_od_vp_esf = fields.Char('Rx final OI DNP')
    rx_final_od_vp_cil = fields.Char('Rx final OI DNP')
    rx_final_oi_vp_esf = fields.Char('Rx final OI DNP')
    rx_final_oi_vp_cil = fields.Char('Rx final OI DNP')
    rx_final_od_av = fields.Char('Rx final od av')
    rx_final_oi_av = fields.Char('Rx final oi av')
    rx_final_od_prisma = fields.Char('Prisma OD')
    rx_final_oi_prisma = fields.Char('Prisma OI')
    ### RX FINAL ###

    prismas = fields.Char('Prismas', size=128)
    tipo_de_lente = fields.Char('Tipo de lente', size=128)
    diagnostico = fields.Char('Diagnostico', size=256)
    plan = fields.Char('Plan de Manejo', size=256)
    ### DIAGNOSTICO ###
    oftalmoscopia = fields.Text()
    dx_primario = fields.Char(string='Dx primario', selection=[
        ('HIPERMETROPIA', 'H520 - HIPERMETROPIA'),
        ('MIOPIA', 'H521 MIOPIA'),
        ('ASTIGMATISMO', 'H522 - ASTIGMATISMO'),
        ('PRESBICIA', 'H524 - PRESBICIA'),
        ('ESTRABISMO CONCOMITANTE CONVERGENTE', 'H500 - ESTRABISMO CONCOMITANTE CONVERGENTE'),
        ('ESTRABISMO CONCOMITANTE DIVERGENTE', 'H501 - ESTRABISMO CONCOMITANTE DIVERGENTE'),
        ('ESTRABISMO VERTICAL', 'H502 - ESTRABISMO VERTICAL'),
        ('HETEROTROPIA INTERMITENTE', 'H503 - HETEROTROPIA INTERMITENTE'),
        ('OTRAS HETEROTROPIAS O LAS NO ESPECIFICADAS', 'H504 - OTRAS HETEROTROPIAS O LAS NO ESPECIFICADAS'),
        ('HETEROFORIA', 'H505 - HETEROFORIA'),
        ('ESTRABISMO MECANICO', 'H506 - ESTRABISMO MECANICO'),
        ('OTROS ESTRABISMOS ESPECIFICADOS', 'H508 - OTROS ESTRABISMOS ESPECIFICADOS'),
        ('ESTRABISMO, NO ESPECIFICADO', 'H509 - ESTRABISMO, NO ESPECIFICADO'),
        ('PARALISIS DE LA CONJUGACION DE LA MIRADA', 'H510 - PARALISIS DE LA CONJUGACION DE LA MIRADA'),
        ('EXCESO E INSUFICIENCIA DE LA CONVERGENCIA OCULAR', 'H511 - EXCESO E INSUFICIENCIA DE LA CONVERGENCIA OCULAR'),
        ('OFTALMOPLEJIA INTERNUCLEAR', 'H512 - OFTALMOPLEJIA INTERNUCLEAR'),
        ('OTROS TRASTORNOS ESPECIFICADOS DE LOS MOVIMIENTOS BINOCULARES',
         'H518 - OTROS TRASTORNOS ESPECIFICADOS DE LOS MOVIMIENTOS BINOCULARES'),
        ('TRASTORNOS DEL MOVIMIENTO BINOCULAR, NO ESPECIFICADO',
         'H519 - TRASTORNOS DEL MOVIMIENTO BINOCULAR, NO ESPECIFICADO'),
        ('ANISOMETROPIA Y ANISEICONIA', 'H523 - ANISOMETROPIA Y ANISEICONIA'),
        ('TRASTORNOS DE LA ACOMODACION', 'H525 - TRASTORNOS DE LA ACOMODACION'),
        ('OTROS TRASTORNOS DE LA REFRACCION', 'H526 - OTROS TRASTORNOS DE LA REFRACCION'),
        ('TRASTORNO DE LA REFRACCION, NO ESPECIFICADO', 'H527 - TRASTORNO DE LA REFRACCION, NO ESPECIFICADO'),
        ('AMBLIOPIA EX ANOPSIA', 'H530 - AMBLIOPIA EX ANOPSIA'),
        ('ALTERACIONES VISUALES SUBJETIVAS', 'H531 - ALTERACIONES VISUALES SUBJETIVAS'),
        ('DIPLOPIA', 'H532 - DIPLOPIA'),
        ('OTROS TRASTORNOS DE LA VISION BINOCULAR', 'H533 - OTROS TRASTORNOS DE LA VISION BINOCULAR'),
        ('DEFECTOS DEL CAMPO VISUAL', 'H534 - DEFECTOS DEL CAMPO VISUAL'),
        ('DEFICIENCIAS DE LA VISION CROMATICA', 'H535 - DEFICIENCIAS DE LA VISION CROMATICA'),
        ('CEGUERA NOCTURNA', 'H536 - CEGUERA NOCTURNA'),
        ('OTRAS ALTERACIONES VISUALES', 'H538 - OTRAS ALTERACIONES VISUALES'),
        ('ALTERACION VISUAL, NO ESPECIFICADA', 'H539 - ALTERACION VISUAL, NO ESPECIFICADA'),
        ('CEGUERA DE AMBOS OJOS', 'H540 - CEGUERA DE AMBOS OJOS'),
        ('CEGUERA DE UN OJO, VISION SUBNORMAL DEL OTRO', 'H541 - CEGUERA DE UN OJO, VISION SUBNORMAL DEL OTRO'),
        ('VISION  SUBNORMAL DE AMBOS OJOS', 'H542 - VISION  SUBNORMAL DE AMBOS OJOS'),
        ('DISMINUCION INDETERMINADA DE LA AGUDEZA VISUAL EN AMBOS  OJOS',
         'H543 - DISMINUCION INDETERMINADA DE LA AGUDEZA VISUAL EN AMBOS  OJOS'),
        ('CEGUERA  DE UN OJO', 'H544 - CEGUERA  DE UN OJO'),
        ('VISION SUBNORMAL DE UN OJO', 'H545 - VISION SUBNORMAL DE UN OJO'),
        ('DISMINUCION  INDETERMINADA DE LA AGUDEZA VISUAL DE UN  OJO',
         'H546 - DISMINUCION  INDETERMINADA DE LA AGUDEZA VISUAL DE UN  OJO'),
        ('DISMINUCION DE LA AGUDEZA VISUAL, SIN ESPECIFICACION',
         'H547 - DISMINUCION DE LA AGUDEZA VISUAL, SIN ESPECIFICACION'),
        ('NISTAGMO Y OTROS MOVIMIENTOS OCULARES IRREGULARES',
         'H55X - NISTAGMO Y OTROS MOVIMIENTOS OCULARES IRREGULARES'),
        ('ANOMALIAS DE LA FUNCION PUPILAR', 'H570 - ANOMALIAS DE LA FUNCION PUPILAR'),
        ('HIPERMETROPIA', 'H520 - HIPERMETROPIA'),
        ('MIOPIA', 'H521 MIOPIA'),
        ('ASTIGMATISMO', 'H522 - ASTIGMATISMO'),
        ('PRESBICIA', 'H524 - PRESBICIA'),
        ('ESTRABISMO CONCOMITANTE CONVERGENTE', 'H500 - ESTRABISMO CONCOMITANTE CONVERGENTE'),
        ('ESTRABISMO CONCOMITANTE DIVERGENTE', 'H501 - ESTRABISMO CONCOMITANTE DIVERGENTE'),
        ('ESTRABISMO VERTICAL', 'H502 - ESTRABISMO VERTICAL'),
        ('HETEROTROPIA INTERMITENTE', 'H503 - HETEROTROPIA INTERMITENTE'),
        ('OTRAS HETEROTROPIAS O LAS NO ESPECIFICADAS', 'H504 - OTRAS HETEROTROPIAS O LAS NO ESPECIFICADAS'),
        ('HETEROFORIA', 'H505 - HETEROFORIA'),
        ('ESTRABISMO MECANICO', 'H506 - ESTRABISMO MECANICO'),
        ('OTROS ESTRABISMOS ESPECIFICADOS', 'H508 - OTROS ESTRABISMOS ESPECIFICADOS'),
        ('ESTRABISMO, NO ESPECIFICADO', 'H509 - ESTRABISMO, NO ESPECIFICADO'),
        ('PARALISIS DE LA CONJUGACION DE LA MIRADA', 'H510 - PARALISIS DE LA CONJUGACION DE LA MIRADA'),
        ('EXCESO E INSUFICIENCIA DE LA CONVERGENCIA OCULAR', 'H511 - EXCESO E INSUFICIENCIA DE LA CONVERGENCIA OCULAR'),
        ('OFTALMOPLEJIA INTERNUCLEAR', 'H512 - OFTALMOPLEJIA INTERNUCLEAR'),
        ('OTROS TRASTORNOS ESPECIFICADOS DE LOS MOVIMIENTOS BINOCULARES',
         'H518 - OTROS TRASTORNOS ESPECIFICADOS DE LOS MOVIMIENTOS BINOCULARES'),
        ('TRASTORNOS DEL MOVIMIENTO BINOCULAR, NO ESPECIFICADO',
         'H519 - TRASTORNOS DEL MOVIMIENTO BINOCULAR, NO ESPECIFICADO'),
        ('ANISOMETROPIA Y ANISEICONIA', 'H523 - ANISOMETROPIA Y ANISEICONIA'),
        ('TRASTORNOS DE LA ACOMODACION', 'H525 - TRASTORNOS DE LA ACOMODACION'),
        ('OTROS TRASTORNOS DE LA REFRACCION', 'H526 - OTROS TRASTORNOS DE LA REFRACCION'),
        ('TRASTORNO DE LA REFRACCION, NO ESPECIFICADO', 'H527 - TRASTORNO DE LA REFRACCION, NO ESPECIFICADO'),
        ('AMBLIOPIA EX ANOPSIA', 'H530 - AMBLIOPIA EX ANOPSIA'),
        ('ALTERACIONES VISUALES SUBJETIVAS', 'H531 - ALTERACIONES VISUALES SUBJETIVAS'),
        ('DIPLOPIA', 'H532 - DIPLOPIA'),
        ('OTROS TRASTORNOS DE LA VISION BINOCULAR', 'H533 - OTROS TRASTORNOS DE LA VISION BINOCULAR'),
        ('DEFECTOS DEL CAMPO VISUAL', 'H534 - DEFECTOS DEL CAMPO VISUAL'),
        ('DEFICIENCIAS DE LA VISION CROMATICA', 'H535 - DEFICIENCIAS DE LA VISION CROMATICA'),
        ('CEGUERA NOCTURNA', 'H536 - CEGUERA NOCTURNA'),
        ('OTRAS ALTERACIONES VISUALES', 'H538 - OTRAS ALTERACIONES VISUALES'),
        ('ALTERACION VISUAL, NO ESPECIFICADA', 'H539 - ALTERACION VISUAL, NO ESPECIFICADA'),
        ('CEGUERA DE AMBOS OJOS', 'H540 - CEGUERA DE AMBOS OJOS'),
        ('CEGUERA DE UN OJO, VISION SUBNORMAL DEL OTRO', 'H541 - CEGUERA DE UN OJO, VISION SUBNORMAL DEL OTRO'),
        ('VISION  SUBNORMAL DE AMBOS OJOS', 'H542 - VISION  SUBNORMAL DE AMBOS OJOS'),
        ('DISMINUCION INDETERMINADA DE LA AGUDEZA VISUAL EN AMBOS  OJOS',
         'H543 - DISMINUCION INDETERMINADA DE LA AGUDEZA VISUAL EN AMBOS  OJOS'),
        ('CEGUERA  DE UN OJO', 'H544 - CEGUERA  DE UN OJO'),
        ('VISION SUBNORMAL DE UN OJO', 'H545 - VISION SUBNORMAL DE UN OJO'),
        ('DISMINUCION  INDETERMINADA DE LA AGUDEZA VISUAL DE UN  OJO',
         'H546 - DISMINUCION  INDETERMINADA DE LA AGUDEZA VISUAL DE UN  OJO'),
        ('DISMINUCION DE LA AGUDEZA VISUAL, SIN ESPECIFICACION',
         'H547 - DISMINUCION DE LA AGUDEZA VISUAL, SIN ESPECIFICACION'),
        ('NISTAGMO Y OTROS MOVIMIENTOS OCULARES IRREGULARES',
         'H55X - NISTAGMO Y OTROS MOVIMIENTOS OCULARES IRREGULARES'),
        ('ANOMALIAS DE LA FUNCION PUPILAR', 'H570 - ANOMALIAS DE LA FUNCION PUPILAR'),
        ('DOLOR OCULAR', 'H571 - DOLOR OCULAR'),
        ('OTROS TRASTORNOS ESPECIFICADOS DEL OJO Y SUS ANEXOS',
         'H578 - OTROS TRASTORNOS ESPECIFICADOS DEL OJO Y SUS ANEXOS'),
        ('TRASTORNO DEL OJO Y SUS ANEXOS, NO ESPECIFICADO', 'H579 - TRASTORNO DEL OJO Y SUS ANEXOS, NO ESPECIFICADO'),
        ('NOMALIAS DE LA FUNCION PUPILAR EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H580 - NOMALIAS DE LA FUNCION PUPILAR EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('ALTERACIONES  DE LA VISION EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H581 - ALTERACIONES  DE LA VISION EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('OTROS TRASTORNOS ESPECIFICADOS DEL OJO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H588 - OTROS TRASTORNOS ESPECIFICADOS DEL OJO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('SINDROME VITREO CONSECUTIVO A CIRUGIA DE CATARATA',
         'H590 - SINDROME VITREO CONSECUTIVO A CIRUGIA DE CATARATA'),
        ('OTROS TRASTORNOS DEL OJO Y SUS ANEXOS, CONSECUTIVOS A PROCEDIMIENTOS',
         'H598 - OTROS TRASTORNOS DEL OJO Y SUS ANEXOS, CONSECUTIVOS A PROCEDIMIENTOS'),
        ('TRASTORNO NO ESPECIFICADO DEL OJO Y SUS ANEXOS, CONSECUTIVO A PROCEDIMIENTOS',
         'H599 - TRASTORNO NO ESPECIFICADO DEL OJO Y SUS ANEXOS, CONSECUTIVO A PROCEDIMIENTOS'),
        ('DOLOR OCULAR', 'H571 - DOLOR OCULAR'),
        ('OTROS TRASTORNOS ESPECIFICADOS DEL OJO Y SUS ANEXOS',
         'H578 - OTROS TRASTORNOS ESPECIFICADOS DEL OJO Y SUS ANEXOS'),
        ('TRASTORNO DEL OJO Y SUS ANEXOS, NO ESPECIFICADO', 'H579 - TRASTORNO DEL OJO Y SUS ANEXOS, NO ESPECIFICADO'),
        ('NOMALIAS DE LA FUNCION PUPILAR EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H580 - NOMALIAS DE LA FUNCION PUPILAR EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('ALTERACIONES  DE LA VISION EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H581 - ALTERACIONES  DE LA VISION EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('OTROS TRASTORNOS ESPECIFICADOS DEL OJO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H588 - OTROS TRASTORNOS ESPECIFICADOS DEL OJO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('SINDROME VITREO CONSECUTIVO A CIRUGIA DE CATARATA',
         'H590 - SINDROME VITREO CONSECUTIVO A CIRUGIA DE CATARATA'),
        ('OTROS TRASTORNOS DEL OJO Y SUS ANEXOS, CONSECUTIVOS A PROCEDIMIENTOS',
         'H598 - OTROS TRASTORNOS DEL OJO Y SUS ANEXOS, CONSECUTIVOS A PROCEDIMIENTOS'),
        ('TRASTORNO NO ESPECIFICADO DEL OJO Y SUS ANEXOS, CONSECUTIVO A PROCEDIMIENTOS',
         'H599 - TRASTORNO NO ESPECIFICADO DEL OJO Y SUS ANEXOS, CONSECUTIVO A PROCEDIMIENTOS'),

    ])
    dx_secundario = fields.Char(string='Dx Secundario', selection=[
        ('HIPERMETROPIA', 'H520 - HIPERMETROPIA'),
        ('MIOPIA', 'H521 MIOPIA'),
        ('ASTIGMATISMO', 'H522 - ASTIGMATISMO'),
        ('PRESBICIA', 'H524 - PRESBICIA'),
        ('ESTRABISMO CONCOMITANTE CONVERGENTE', 'H500 - ESTRABISMO CONCOMITANTE CONVERGENTE'),
        ('ESTRABISMO CONCOMITANTE DIVERGENTE', 'H501 - ESTRABISMO CONCOMITANTE DIVERGENTE'),
        ('ESTRABISMO VERTICAL', 'H502 - ESTRABISMO VERTICAL'),
        ('HETEROTROPIA INTERMITENTE', 'H503 - HETEROTROPIA INTERMITENTE'),
        ('OTRAS HETEROTROPIAS O LAS NO ESPECIFICADAS', 'H504 - OTRAS HETEROTROPIAS O LAS NO ESPECIFICADAS'),
        ('HETEROFORIA', 'H505 - HETEROFORIA'),
        ('ESTRABISMO MECANICO', 'H506 - ESTRABISMO MECANICO'),
        ('OTROS ESTRABISMOS ESPECIFICADOS', 'H508 - OTROS ESTRABISMOS ESPECIFICADOS'),
        ('ESTRABISMO, NO ESPECIFICADO', 'H509 - ESTRABISMO, NO ESPECIFICADO'),
        ('PARALISIS DE LA CONJUGACION DE LA MIRADA', 'H510 - PARALISIS DE LA CONJUGACION DE LA MIRADA'),
        ('EXCESO E INSUFICIENCIA DE LA CONVERGENCIA OCULAR', 'H511 - EXCESO E INSUFICIENCIA DE LA CONVERGENCIA OCULAR'),
        ('OFTALMOPLEJIA INTERNUCLEAR', 'H512 - OFTALMOPLEJIA INTERNUCLEAR'),
        ('OTROS TRASTORNOS ESPECIFICADOS DE LOS MOVIMIENTOS BINOCULARES',
         'H518 - OTROS TRASTORNOS ESPECIFICADOS DE LOS MOVIMIENTOS BINOCULARES'),
        ('TRASTORNOS DEL MOVIMIENTO BINOCULAR, NO ESPECIFICADO',
         'H519 - TRASTORNOS DEL MOVIMIENTO BINOCULAR, NO ESPECIFICADO'),
        ('ANISOMETROPIA Y ANISEICONIA', 'H523 - ANISOMETROPIA Y ANISEICONIA'),
        ('TRASTORNOS DE LA ACOMODACION', 'H525 - TRASTORNOS DE LA ACOMODACION'),
        ('OTROS TRASTORNOS DE LA REFRACCION', 'H526 - OTROS TRASTORNOS DE LA REFRACCION'),
        ('TRASTORNO DE LA REFRACCION, NO ESPECIFICADO', 'H527 - TRASTORNO DE LA REFRACCION, NO ESPECIFICADO'),
        ('AMBLIOPIA EX ANOPSIA', 'H530 - AMBLIOPIA EX ANOPSIA'),
        ('ALTERACIONES VISUALES SUBJETIVAS', 'H531 - ALTERACIONES VISUALES SUBJETIVAS'),
        ('DIPLOPIA', 'H532 - DIPLOPIA'),
        ('OTROS TRASTORNOS DE LA VISION BINOCULAR', 'H533 - OTROS TRASTORNOS DE LA VISION BINOCULAR'),
        ('DEFECTOS DEL CAMPO VISUAL', 'H534 - DEFECTOS DEL CAMPO VISUAL'),
        ('DEFICIENCIAS DE LA VISION CROMATICA', 'H535 - DEFICIENCIAS DE LA VISION CROMATICA'),
        ('CEGUERA NOCTURNA', 'H536 - CEGUERA NOCTURNA'),
        ('OTRAS ALTERACIONES VISUALES', 'H538 - OTRAS ALTERACIONES VISUALES'),
        ('ALTERACION VISUAL, NO ESPECIFICADA', 'H539 - ALTERACION VISUAL, NO ESPECIFICADA'),
        ('CEGUERA DE AMBOS OJOS', 'H540 - CEGUERA DE AMBOS OJOS'),
        ('CEGUERA DE UN OJO, VISION SUBNORMAL DEL OTRO', 'H541 - CEGUERA DE UN OJO, VISION SUBNORMAL DEL OTRO'),
        ('VISION  SUBNORMAL DE AMBOS OJOS', 'H542 - VISION  SUBNORMAL DE AMBOS OJOS'),
        ('DISMINUCION INDETERMINADA DE LA AGUDEZA VISUAL EN AMBOS  OJOS',
         'H543 - DISMINUCION INDETERMINADA DE LA AGUDEZA VISUAL EN AMBOS  OJOS'),
        ('CEGUERA  DE UN OJO', 'H544 - CEGUERA  DE UN OJO'),
        ('VISION SUBNORMAL DE UN OJO', 'H545 - VISION SUBNORMAL DE UN OJO'),
        ('DISMINUCION  INDETERMINADA DE LA AGUDEZA VISUAL DE UN  OJO',
         'H546 - DISMINUCION  INDETERMINADA DE LA AGUDEZA VISUAL DE UN  OJO'),
        ('DISMINUCION DE LA AGUDEZA VISUAL, SIN ESPECIFICACION',
         'H547 - DISMINUCION DE LA AGUDEZA VISUAL, SIN ESPECIFICACION'),
        ('NISTAGMO Y OTROS MOVIMIENTOS OCULARES IRREGULARES',
         'H55X - NISTAGMO Y OTROS MOVIMIENTOS OCULARES IRREGULARES'),
        ('ANOMALIAS DE LA FUNCION PUPILAR', 'H570 - ANOMALIAS DE LA FUNCION PUPILAR'),
        ('HIPERMETROPIA','H520 - HIPERMETROPIA'),
        ('MIOPIA', 'H521 MIOPIA'),
        ('ASTIGMATISMO', 'H522 - ASTIGMATISMO'),
        ('PRESBICIA', 'H524 - PRESBICIA'),
        ('ESTRABISMO CONCOMITANTE CONVERGENTE', 'H500 - ESTRABISMO CONCOMITANTE CONVERGENTE'),
        ('ESTRABISMO CONCOMITANTE DIVERGENTE', 'H501 - ESTRABISMO CONCOMITANTE DIVERGENTE'),
        ('ESTRABISMO VERTICAL', 'H502 - ESTRABISMO VERTICAL'),
        ('HETEROTROPIA INTERMITENTE', 'H503 - HETEROTROPIA INTERMITENTE'),
        ('OTRAS HETEROTROPIAS O LAS NO ESPECIFICADAS', 'H504 - OTRAS HETEROTROPIAS O LAS NO ESPECIFICADAS'),
        ('HETEROFORIA', 'H505 - HETEROFORIA'),
        ('ESTRABISMO MECANICO', 'H506 - ESTRABISMO MECANICO'),
        ('OTROS ESTRABISMOS ESPECIFICADOS', 'H508 - OTROS ESTRABISMOS ESPECIFICADOS'),
        ('ESTRABISMO, NO ESPECIFICADO', 'H509 - ESTRABISMO, NO ESPECIFICADO'),
        ('PARALISIS DE LA CONJUGACION DE LA MIRADA', 'H510 - PARALISIS DE LA CONJUGACION DE LA MIRADA'),
        ('EXCESO E INSUFICIENCIA DE LA CONVERGENCIA OCULAR', 'H511 - EXCESO E INSUFICIENCIA DE LA CONVERGENCIA OCULAR'),
        ('OFTALMOPLEJIA INTERNUCLEAR', 'H512 - OFTALMOPLEJIA INTERNUCLEAR'),
        ('OTROS TRASTORNOS ESPECIFICADOS DE LOS MOVIMIENTOS BINOCULARES',
         'H518 - OTROS TRASTORNOS ESPECIFICADOS DE LOS MOVIMIENTOS BINOCULARES'),
        ('TRASTORNOS DEL MOVIMIENTO BINOCULAR, NO ESPECIFICADO',
         'H519 - TRASTORNOS DEL MOVIMIENTO BINOCULAR, NO ESPECIFICADO'),
        ('ANISOMETROPIA Y ANISEICONIA', 'H523 - ANISOMETROPIA Y ANISEICONIA'),
        ('TRASTORNOS DE LA ACOMODACION', 'H525 - TRASTORNOS DE LA ACOMODACION'),
        ('OTROS TRASTORNOS DE LA REFRACCION', 'H526 - OTROS TRASTORNOS DE LA REFRACCION'),
        ('TRASTORNO DE LA REFRACCION, NO ESPECIFICADO', 'H527 - TRASTORNO DE LA REFRACCION, NO ESPECIFICADO'),
        ('AMBLIOPIA EX ANOPSIA', 'H530 - AMBLIOPIA EX ANOPSIA'),
        ('ALTERACIONES VISUALES SUBJETIVAS', 'H531 - ALTERACIONES VISUALES SUBJETIVAS'),
        ('DIPLOPIA', 'H532 - DIPLOPIA'),
        ('OTROS TRASTORNOS DE LA VISION BINOCULAR', 'H533 - OTROS TRASTORNOS DE LA VISION BINOCULAR'),
        ('DEFECTOS DEL CAMPO VISUAL', 'H534 - DEFECTOS DEL CAMPO VISUAL'),
        ('DEFICIENCIAS DE LA VISION CROMATICA', 'H535 - DEFICIENCIAS DE LA VISION CROMATICA'),
        ('CEGUERA NOCTURNA', 'H536 - CEGUERA NOCTURNA'),
        ('OTRAS ALTERACIONES VISUALES', 'H538 - OTRAS ALTERACIONES VISUALES'),
        ('ALTERACION VISUAL, NO ESPECIFICADA', 'H539 - ALTERACION VISUAL, NO ESPECIFICADA'),
        ('CEGUERA DE AMBOS OJOS', 'H540 - CEGUERA DE AMBOS OJOS'),
        ('CEGUERA DE UN OJO, VISION SUBNORMAL DEL OTRO', 'H541 - CEGUERA DE UN OJO, VISION SUBNORMAL DEL OTRO'),
        ('VISION  SUBNORMAL DE AMBOS OJOS', 'H542 - VISION  SUBNORMAL DE AMBOS OJOS'),
        ('DISMINUCION INDETERMINADA DE LA AGUDEZA VISUAL EN AMBOS  OJOS',
         'H543 - DISMINUCION INDETERMINADA DE LA AGUDEZA VISUAL EN AMBOS  OJOS'),
        ('CEGUERA  DE UN OJO', 'H544 - CEGUERA  DE UN OJO'),
        ('VISION SUBNORMAL DE UN OJO', 'H545 - VISION SUBNORMAL DE UN OJO'),
        ('DISMINUCION  INDETERMINADA DE LA AGUDEZA VISUAL DE UN  OJO',
         'H546 - DISMINUCION  INDETERMINADA DE LA AGUDEZA VISUAL DE UN  OJO'),
        ('DISMINUCION DE LA AGUDEZA VISUAL, SIN ESPECIFICACION',
         'H547 - DISMINUCION DE LA AGUDEZA VISUAL, SIN ESPECIFICACION'),
        ('NISTAGMO Y OTROS MOVIMIENTOS OCULARES IRREGULARES',
         'H55X - NISTAGMO Y OTROS MOVIMIENTOS OCULARES IRREGULARES'),
        ('ANOMALIAS DE LA FUNCION PUPILAR', 'H570 - ANOMALIAS DE LA FUNCION PUPILAR'),
        ('DOLOR OCULAR', 'H571 - DOLOR OCULAR'),
        ('OTROS TRASTORNOS ESPECIFICADOS DEL OJO Y SUS ANEXOS',
         'H578 - OTROS TRASTORNOS ESPECIFICADOS DEL OJO Y SUS ANEXOS'),
        ('TRASTORNO DEL OJO Y SUS ANEXOS, NO ESPECIFICADO', 'H579 - TRASTORNO DEL OJO Y SUS ANEXOS, NO ESPECIFICADO'),
        ('NOMALIAS DE LA FUNCION PUPILAR EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H580 - NOMALIAS DE LA FUNCION PUPILAR EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('ALTERACIONES  DE LA VISION EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H581 - ALTERACIONES  DE LA VISION EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('OTROS TRASTORNOS ESPECIFICADOS DEL OJO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H588 - OTROS TRASTORNOS ESPECIFICADOS DEL OJO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('SINDROME VITREO CONSECUTIVO A CIRUGIA DE CATARATA',
         'H590 - SINDROME VITREO CONSECUTIVO A CIRUGIA DE CATARATA'),
        ('OTROS TRASTORNOS DEL OJO Y SUS ANEXOS, CONSECUTIVOS A PROCEDIMIENTOS',
         'H598 - OTROS TRASTORNOS DEL OJO Y SUS ANEXOS, CONSECUTIVOS A PROCEDIMIENTOS'),
        ('TRASTORNO NO ESPECIFICADO DEL OJO Y SUS ANEXOS, CONSECUTIVO A PROCEDIMIENTOS',
         'H599 - TRASTORNO NO ESPECIFICADO DEL OJO Y SUS ANEXOS, CONSECUTIVO A PROCEDIMIENTOS'),
        ('DOLOR OCULAR', 'H571 - DOLOR OCULAR'),
        ('OTROS TRASTORNOS ESPECIFICADOS DEL OJO Y SUS ANEXOS',
         'H578 - OTROS TRASTORNOS ESPECIFICADOS DEL OJO Y SUS ANEXOS'),
        ('TRASTORNO DEL OJO Y SUS ANEXOS, NO ESPECIFICADO', 'H579 - TRASTORNO DEL OJO Y SUS ANEXOS, NO ESPECIFICADO'),
        ('NOMALIAS DE LA FUNCION PUPILAR EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H580 - NOMALIAS DE LA FUNCION PUPILAR EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('ALTERACIONES  DE LA VISION EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H581 - ALTERACIONES  DE LA VISION EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('OTROS TRASTORNOS ESPECIFICADOS DEL OJO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H588 - OTROS TRASTORNOS ESPECIFICADOS DEL OJO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('SINDROME VITREO CONSECUTIVO A CIRUGIA DE CATARATA',
         'H590 - SINDROME VITREO CONSECUTIVO A CIRUGIA DE CATARATA'),
        ('OTROS TRASTORNOS DEL OJO Y SUS ANEXOS, CONSECUTIVOS A PROCEDIMIENTOS',
         'H598 - OTROS TRASTORNOS DEL OJO Y SUS ANEXOS, CONSECUTIVOS A PROCEDIMIENTOS'),
        ('TRASTORNO NO ESPECIFICADO DEL OJO Y SUS ANEXOS, CONSECUTIVO A PROCEDIMIENTOS',
         'H599 - TRASTORNO NO ESPECIFICADO DEL OJO Y SUS ANEXOS, CONSECUTIVO A PROCEDIMIENTOS'),

    ])
    dx_terciario = fields.Char(string='Dx Terciario', selection=[
        ('HIPERMETROPIA', 'H520 - HIPERMETROPIA'),
        ('MIOPIA', 'H521 MIOPIA'),
        ('ASTIGMATISMO', 'H522 - ASTIGMATISMO'),
        ('PRESBICIA', 'H524 - PRESBICIA'),
        ('ESTRABISMO CONCOMITANTE CONVERGENTE', 'H500 - ESTRABISMO CONCOMITANTE CONVERGENTE'),
        ('ESTRABISMO CONCOMITANTE DIVERGENTE', 'H501 - ESTRABISMO CONCOMITANTE DIVERGENTE'),
        ('ESTRABISMO VERTICAL', 'H502 - ESTRABISMO VERTICAL'),
        ('HETEROTROPIA INTERMITENTE', 'H503 - HETEROTROPIA INTERMITENTE'),
        ('OTRAS HETEROTROPIAS O LAS NO ESPECIFICADAS', 'H504 - OTRAS HETEROTROPIAS O LAS NO ESPECIFICADAS'),
        ('HETEROFORIA', 'H505 - HETEROFORIA'),
        ('ESTRABISMO MECANICO', 'H506 - ESTRABISMO MECANICO'),
        ('OTROS ESTRABISMOS ESPECIFICADOS', 'H508 - OTROS ESTRABISMOS ESPECIFICADOS'),
        ('ESTRABISMO, NO ESPECIFICADO', 'H509 - ESTRABISMO, NO ESPECIFICADO'),
        ('PARALISIS DE LA CONJUGACION DE LA MIRADA', 'H510 - PARALISIS DE LA CONJUGACION DE LA MIRADA'),
        ('EXCESO E INSUFICIENCIA DE LA CONVERGENCIA OCULAR', 'H511 - EXCESO E INSUFICIENCIA DE LA CONVERGENCIA OCULAR'),
        ('OFTALMOPLEJIA INTERNUCLEAR', 'H512 - OFTALMOPLEJIA INTERNUCLEAR'),
        ('OTROS TRASTORNOS ESPECIFICADOS DE LOS MOVIMIENTOS BINOCULARES',
         'H518 - OTROS TRASTORNOS ESPECIFICADOS DE LOS MOVIMIENTOS BINOCULARES'),
        ('TRASTORNOS DEL MOVIMIENTO BINOCULAR, NO ESPECIFICADO',
         'H519 - TRASTORNOS DEL MOVIMIENTO BINOCULAR, NO ESPECIFICADO'),
        ('ANISOMETROPIA Y ANISEICONIA', 'H523 - ANISOMETROPIA Y ANISEICONIA'),
        ('TRASTORNOS DE LA ACOMODACION', 'H525 - TRASTORNOS DE LA ACOMODACION'),
        ('OTROS TRASTORNOS DE LA REFRACCION', 'H526 - OTROS TRASTORNOS DE LA REFRACCION'),
        ('TRASTORNO DE LA REFRACCION, NO ESPECIFICADO', 'H527 - TRASTORNO DE LA REFRACCION, NO ESPECIFICADO'),
        ('AMBLIOPIA EX ANOPSIA', 'H530 - AMBLIOPIA EX ANOPSIA'),
        ('ALTERACIONES VISUALES SUBJETIVAS', 'H531 - ALTERACIONES VISUALES SUBJETIVAS'),
        ('DIPLOPIA', 'H532 - DIPLOPIA'),
        ('OTROS TRASTORNOS DE LA VISION BINOCULAR', 'H533 - OTROS TRASTORNOS DE LA VISION BINOCULAR'),
        ('DEFECTOS DEL CAMPO VISUAL', 'H534 - DEFECTOS DEL CAMPO VISUAL'),
        ('DEFICIENCIAS DE LA VISION CROMATICA', 'H535 - DEFICIENCIAS DE LA VISION CROMATICA'),
        ('CEGUERA NOCTURNA', 'H536 - CEGUERA NOCTURNA'),
        ('OTRAS ALTERACIONES VISUALES', 'H538 - OTRAS ALTERACIONES VISUALES'),
        ('ALTERACION VISUAL, NO ESPECIFICADA', 'H539 - ALTERACION VISUAL, NO ESPECIFICADA'),
        ('CEGUERA DE AMBOS OJOS', 'H540 - CEGUERA DE AMBOS OJOS'),
        ('CEGUERA DE UN OJO, VISION SUBNORMAL DEL OTRO', 'H541 - CEGUERA DE UN OJO, VISION SUBNORMAL DEL OTRO'),
        ('VISION  SUBNORMAL DE AMBOS OJOS', 'H542 - VISION  SUBNORMAL DE AMBOS OJOS'),
        ('DISMINUCION INDETERMINADA DE LA AGUDEZA VISUAL EN AMBOS  OJOS',
         'H543 - DISMINUCION INDETERMINADA DE LA AGUDEZA VISUAL EN AMBOS  OJOS'),
        ('CEGUERA  DE UN OJO', 'H544 - CEGUERA  DE UN OJO'),
        ('VISION SUBNORMAL DE UN OJO', 'H545 - VISION SUBNORMAL DE UN OJO'),
        ('DISMINUCION  INDETERMINADA DE LA AGUDEZA VISUAL DE UN  OJO',
         'H546 - DISMINUCION  INDETERMINADA DE LA AGUDEZA VISUAL DE UN  OJO'),
        ('DISMINUCION DE LA AGUDEZA VISUAL, SIN ESPECIFICACION',
         'H547 - DISMINUCION DE LA AGUDEZA VISUAL, SIN ESPECIFICACION'),
        ('NISTAGMO Y OTROS MOVIMIENTOS OCULARES IRREGULARES',
         'H55X - NISTAGMO Y OTROS MOVIMIENTOS OCULARES IRREGULARES'),
        ('ANOMALIAS DE LA FUNCION PUPILAR', 'H570 - ANOMALIAS DE LA FUNCION PUPILAR'),
        ('HIPERMETROPIA', 'H520 - HIPERMETROPIA'),
        ('MIOPIA', 'H521 MIOPIA'),
        ('ASTIGMATISMO', 'H522 - ASTIGMATISMO'),
        ('PRESBICIA', 'H524 - PRESBICIA'),
        ('ESTRABISMO CONCOMITANTE CONVERGENTE', 'H500 - ESTRABISMO CONCOMITANTE CONVERGENTE'),
        ('ESTRABISMO CONCOMITANTE DIVERGENTE', 'H501 - ESTRABISMO CONCOMITANTE DIVERGENTE'),
        ('ESTRABISMO VERTICAL', 'H502 - ESTRABISMO VERTICAL'),
        ('HETEROTROPIA INTERMITENTE', 'H503 - HETEROTROPIA INTERMITENTE'),
        ('OTRAS HETEROTROPIAS O LAS NO ESPECIFICADAS', 'H504 - OTRAS HETEROTROPIAS O LAS NO ESPECIFICADAS'),
        ('HETEROFORIA', 'H505 - HETEROFORIA'),
        ('ESTRABISMO MECANICO', 'H506 - ESTRABISMO MECANICO'),
        ('OTROS ESTRABISMOS ESPECIFICADOS', 'H508 - OTROS ESTRABISMOS ESPECIFICADOS'),
        ('ESTRABISMO, NO ESPECIFICADO', 'H509 - ESTRABISMO, NO ESPECIFICADO'),
        ('PARALISIS DE LA CONJUGACION DE LA MIRADA', 'H510 - PARALISIS DE LA CONJUGACION DE LA MIRADA'),
        ('EXCESO E INSUFICIENCIA DE LA CONVERGENCIA OCULAR', 'H511 - EXCESO E INSUFICIENCIA DE LA CONVERGENCIA OCULAR'),
        ('OFTALMOPLEJIA INTERNUCLEAR', 'H512 - OFTALMOPLEJIA INTERNUCLEAR'),
        ('OTROS TRASTORNOS ESPECIFICADOS DE LOS MOVIMIENTOS BINOCULARES',
         'H518 - OTROS TRASTORNOS ESPECIFICADOS DE LOS MOVIMIENTOS BINOCULARES'),
        ('TRASTORNOS DEL MOVIMIENTO BINOCULAR, NO ESPECIFICADO',
         'H519 - TRASTORNOS DEL MOVIMIENTO BINOCULAR, NO ESPECIFICADO'),
        ('ANISOMETROPIA Y ANISEICONIA', 'H523 - ANISOMETROPIA Y ANISEICONIA'),
        ('TRASTORNOS DE LA ACOMODACION', 'H525 - TRASTORNOS DE LA ACOMODACION'),
        ('OTROS TRASTORNOS DE LA REFRACCION', 'H526 - OTROS TRASTORNOS DE LA REFRACCION'),
        ('TRASTORNO DE LA REFRACCION, NO ESPECIFICADO', 'H527 - TRASTORNO DE LA REFRACCION, NO ESPECIFICADO'),
        ('AMBLIOPIA EX ANOPSIA', 'H530 - AMBLIOPIA EX ANOPSIA'),
        ('ALTERACIONES VISUALES SUBJETIVAS', 'H531 - ALTERACIONES VISUALES SUBJETIVAS'),
        ('DIPLOPIA', 'H532 - DIPLOPIA'),
        ('OTROS TRASTORNOS DE LA VISION BINOCULAR', 'H533 - OTROS TRASTORNOS DE LA VISION BINOCULAR'),
        ('DEFECTOS DEL CAMPO VISUAL', 'H534 - DEFECTOS DEL CAMPO VISUAL'),
        ('DEFICIENCIAS DE LA VISION CROMATICA', 'H535 - DEFICIENCIAS DE LA VISION CROMATICA'),
        ('CEGUERA NOCTURNA', 'H536 - CEGUERA NOCTURNA'),
        ('OTRAS ALTERACIONES VISUALES', 'H538 - OTRAS ALTERACIONES VISUALES'),
        ('ALTERACION VISUAL, NO ESPECIFICADA', 'H539 - ALTERACION VISUAL, NO ESPECIFICADA'),
        ('CEGUERA DE AMBOS OJOS', 'H540 - CEGUERA DE AMBOS OJOS'),
        ('CEGUERA DE UN OJO, VISION SUBNORMAL DEL OTRO', 'H541 - CEGUERA DE UN OJO, VISION SUBNORMAL DEL OTRO'),
        ('VISION  SUBNORMAL DE AMBOS OJOS', 'H542 - VISION  SUBNORMAL DE AMBOS OJOS'),
        ('DISMINUCION INDETERMINADA DE LA AGUDEZA VISUAL EN AMBOS  OJOS',
         'H543 - DISMINUCION INDETERMINADA DE LA AGUDEZA VISUAL EN AMBOS  OJOS'),
        ('CEGUERA  DE UN OJO', 'H544 - CEGUERA  DE UN OJO'),
        ('VISION SUBNORMAL DE UN OJO', 'H545 - VISION SUBNORMAL DE UN OJO'),
        ('DISMINUCION  INDETERMINADA DE LA AGUDEZA VISUAL DE UN  OJO',
         'H546 - DISMINUCION  INDETERMINADA DE LA AGUDEZA VISUAL DE UN  OJO'),
        ('DISMINUCION DE LA AGUDEZA VISUAL, SIN ESPECIFICACION',
         'H547 - DISMINUCION DE LA AGUDEZA VISUAL, SIN ESPECIFICACION'),
        ('NISTAGMO Y OTROS MOVIMIENTOS OCULARES IRREGULARES',
         'H55X - NISTAGMO Y OTROS MOVIMIENTOS OCULARES IRREGULARES'),
        ('ANOMALIAS DE LA FUNCION PUPILAR', 'H570 - ANOMALIAS DE LA FUNCION PUPILAR'),
        ('DOLOR OCULAR', 'H571 - DOLOR OCULAR'),
        ('OTROS TRASTORNOS ESPECIFICADOS DEL OJO Y SUS ANEXOS',
         'H578 - OTROS TRASTORNOS ESPECIFICADOS DEL OJO Y SUS ANEXOS'),
        ('TRASTORNO DEL OJO Y SUS ANEXOS, NO ESPECIFICADO', 'H579 - TRASTORNO DEL OJO Y SUS ANEXOS, NO ESPECIFICADO'),
        ('NOMALIAS DE LA FUNCION PUPILAR EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H580 - NOMALIAS DE LA FUNCION PUPILAR EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('ALTERACIONES  DE LA VISION EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H581 - ALTERACIONES  DE LA VISION EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('OTROS TRASTORNOS ESPECIFICADOS DEL OJO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H588 - OTROS TRASTORNOS ESPECIFICADOS DEL OJO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('SINDROME VITREO CONSECUTIVO A CIRUGIA DE CATARATA',
         'H590 - SINDROME VITREO CONSECUTIVO A CIRUGIA DE CATARATA'),
        ('OTROS TRASTORNOS DEL OJO Y SUS ANEXOS, CONSECUTIVOS A PROCEDIMIENTOS',
         'H598 - OTROS TRASTORNOS DEL OJO Y SUS ANEXOS, CONSECUTIVOS A PROCEDIMIENTOS'),
        ('TRASTORNO NO ESPECIFICADO DEL OJO Y SUS ANEXOS, CONSECUTIVO A PROCEDIMIENTOS',
         'H599 - TRASTORNO NO ESPECIFICADO DEL OJO Y SUS ANEXOS, CONSECUTIVO A PROCEDIMIENTOS'),
        ('DOLOR OCULAR', 'H571 - DOLOR OCULAR'),
        ('OTROS TRASTORNOS ESPECIFICADOS DEL OJO Y SUS ANEXOS',
         'H578 - OTROS TRASTORNOS ESPECIFICADOS DEL OJO Y SUS ANEXOS'),
        ('TRASTORNO DEL OJO Y SUS ANEXOS, NO ESPECIFICADO', 'H579 - TRASTORNO DEL OJO Y SUS ANEXOS, NO ESPECIFICADO'),
        ('NOMALIAS DE LA FUNCION PUPILAR EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H580 - NOMALIAS DE LA FUNCION PUPILAR EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('ALTERACIONES  DE LA VISION EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H581 - ALTERACIONES  DE LA VISION EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('OTROS TRASTORNOS ESPECIFICADOS DEL OJO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
         'H588 - OTROS TRASTORNOS ESPECIFICADOS DEL OJO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
        ('SINDROME VITREO CONSECUTIVO A CIRUGIA DE CATARATA',
         'H590 - SINDROME VITREO CONSECUTIVO A CIRUGIA DE CATARATA'),
        ('OTROS TRASTORNOS DEL OJO Y SUS ANEXOS, CONSECUTIVOS A PROCEDIMIENTOS',
         'H598 - OTROS TRASTORNOS DEL OJO Y SUS ANEXOS, CONSECUTIVOS A PROCEDIMIENTOS'),
        ('TRASTORNO NO ESPECIFICADO DEL OJO Y SUS ANEXOS, CONSECUTIVO A PROCEDIMIENTOS',
         'H599 - TRASTORNO NO ESPECIFICADO DEL OJO Y SUS ANEXOS, CONSECUTIVO A PROCEDIMIENTOS'),

    ])
    ### Formula ###

    material = fields.Char('Material', size=128)
    filtros = fields.Char('Filtros', size=128)
    uso = fields.Char('Uso', size=128)
    formula_plan = fields.Char('Plan de Manejo', size=256)
    formula_notas = fields.Text('Notas')
    optometra_id = fields.Many2one('res.users', 'Optometra', domain=[('active', '=', True)])
    folio = fields.Char('Folio', size=128)
    sede = fields.Selection(string="Sede", selection=[
        ('1', 'CHIPICHAPE'),
        ('2', 'UNICENTRO'),
        ('3', 'TECNIOPTICA 2142'),
        ('4', 'TECNIOPTICA 1090'),
        ('5', 'TECNIOPTICA 1195'),
        ('6', 'TECNIOPTICA 1005'),
        ('7', 'PRINCIPAL SAS'),
        ('8', 'COMERCIAL 1189'),
        ('9', 'COMERCIAL 1187'),
    ])
    is_remision = fields.Boolean('	Remitido a especialista ', default=False)
    remision_desc = fields.Text('Motivo de remision')
    especialista_id = fields.Many2one('res.partner', 'Especialista')
    observaciones = fields.Text()
    conducta = fields.Text()

    ### prescripcion y usoo ###
    pres_tipo_lente = fields.Char('Tipo de lente')
    pres_material = fields.Selection([('cr39','CR39'),('policarbonato','Policarbonato')],'Material')
    pres_filtro = fields.Char('filtros')
    pres_uso = fields.Selection([('permanente','Permanente'),('ocacional','Ocacional'),('cerca','Cerca'),('lejos','Lejos')],'Modo de uso.')
    pres_control = fields.Char('Control')
    #Observaciones##
    rx_uso_observaciones = fields.Text('Observaciones')
    refraccion_bajo_observaciones = fields.Text('Observaciones')
    seguimientos_id = fields.Many2one('historial.clinico.seguimiento', string="Seguimientos")
    is_seguimiento = fields.Boolean('Seguimientos')

    @api.multi
    def print_report(self):
    # Method to print sale order report
        historial_ids = self.search([], limit=1).ids
        return self.env.ref(
        'ofimatica_clinical_management.report_custom_template').report_action(historial_ids)

    @api.onchange('partner_id')
    def onchange_partner_id(self):
        paciente = self.partner_id
        historial_check = self.env['historial.clinico'].search([('partner_id', 'like', paciente.id)])
        if historial_check:
            self.tipo_servicio = '2'
        else:
            self.tipo_servicio = '1'
        if self.partner_id and self.partner_id.convenio_id:
            self.convenio_id = self.partner_id.convenio_id.id
        if self.partner_id:
            self.nombre = self.partner_id.name

    @api.onchange('optometra_id')
    def triggerOptometra(self):
        if self.partner_id:
            self.documento = self.partner_id.id_document

    @api.multi
    def cita(self):
        self.state = 'cita'

    @api.multi
    def cancelada(self):
        self.state = 'cancelada'

    @api.multi
    def proceso(self):
        self.state = 'proceso'

    @api.multi
    def cerrada(self):
        self.state = 'cerrada'
        self.documento = self.partner_id.id_document

    @api.onchange('load_default', 'partner_id')
    def onchange_load_defaults(self):
        if self.partner_id:
            ojo_derecho = [(0, 0, {
                'name': 'OD',
                'no_unlink': True,
           }), (0, 0, {
                'name': 'OI',
                'no_unlink': True,

           })]
            ojo_izquierdo = [(0, 0, {
               'name': 'OD',
                'no_unlink': True,
           }), (0, 0, {
                'name': 'OI',
                'no_unlink': True,
            })]
            self.agudeza_derecho_ids = ojo_derecho
            self.agudeza_izquierdo_ids = ojo_izquierdo

    @api.model
    def create(self, vals):
        number = self.env['ir.sequence'].next_by_code('historial.clinicoo')
        vals['folio'] = str(number)
        result = super(HistorialClinico, self).create(vals)
        return result

